name: Build CyberChef

on:
  push:
    branches:
      - main
  release:
    types: [created]

jobs:
  build-macos:
    runs-on: macos-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Build for macOS
        run: npx electron-builder --mac --x64

      - name: Upload macOS Artifact
        uses: actions/upload-artifact@v4
        with:
          name: build-macos
          path: dist/

  build-windows:
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Build for Windows
        run: npx electron-builder --win --x64

      - name: Upload Windows Artifact
        uses: actions/upload-artifact@v4
        with:
          name: build-windows
          path: dist/

  build-linux:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Build for Linux
        run: npx electron-builder --linux --x64

      - name: Upload Linux Artifact
        uses: actions/upload-artifact@v4
        with:
          name: build-linux
          path: dist/
